import type { Metadata } from "next";
import { Space_Mono } from "next/font/google";
import "./globals.css";

const inter = Space_Mono({ subsets: ["latin"], weight: ["700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#C5E4E7] min-h-screen h-full`}>{children}</body>
    </html>
  );
}
